---

- name: Ubuntu DevTool Packages
  apt: >
    pkg={{item}}
    state=present
  with_items:
    - build-essential
    - golang
    - cmake
    - redis-tools
    - nmap
    - docker.io

- name: Grab RVM
  get_url:
    url: https://get.rvm.io 
    dest: /var/tmp/rvm 

- name: Setup RVM
  command: "/bin/bash /var/tmp/rvm"
  args:
    chdir: "/home/{{ ubuntu_user }}"
    creates: "/home/{{ ubuntu_user }}/.rvm"
  become: yes
  become_user: "{{ ubuntu_user }}"

