---
- git:
    repo: https://github.com/maguec/dotfiles.git
    dest: "/home/{{ ubuntu_user }}/.dotfiles"
    force: yes

- name: Fix Dotfiles
  command: "chown -R {{ ubuntu_user }}:{{ ubuntu_user }} /home/{{ ubuntu_user }}/.dotfiles"

- name: Setup Dotfiles
  command: "/home/{{ ubuntu_user }}/.dotfiles/setup.sh"
  args:
    chdir: "/home/{{ ubuntu_user }}"
    creates: "/home/{{ ubuntu_user }}/.vim/bundle/vundle/README.md"
  become: yes
  become_user: "{{ ubuntu_user }}"

- name: Setup Vim
  command: "/usr/bin/vim +BundleInstall +qall"
  args:
    chdir: "/home/{{ ubuntu_user }}"
  become: yes
  become_user: "{{ ubuntu_user }}"

- name: sloppy_focus
  command:  /usr/bin/gsettings set org.gnome.desktop.wm.preferences focus-mode 'mouse'
  become: yes
  become_user: "{{ ubuntu_user }}"

- name: autoraise
  command:  /usr/bin/gsettings set org.gnome.desktop.wm.preferences auto-raise true
  become: yes
  become_user: "{{ ubuntu_user }}"

- name: autoraise_delay
  command:  /usr/bin/gsettings set org.gnome.desktop.wm.preferences auto-raise-delay 500
  become: yes
  become_user: "{{ ubuntu_user }}"
