---
# tasks file for ubuntu-workstation

- { include: create_user.yml,    tags: ["user"], when: create_user }
- { include: prereqs.yml,        tags: ["prereqs"] }
- { include: base_packages.yml,  tags: ["base_packages"] }
- { include: dotfiles.yml,       tags: ["dotfiles"] }
- { include: devtools.yml,       tags: ["devtools"] }
- { include: tfenv.yml,          tags: ["tfenv"] }
- { include: benchmarktools.yml, tags: ["benchmarktools"] }
- { include: gui_packages.yml,   tags: ["gui_packages"], when: gui_install }
- { include: google.yml,         tags: ["google"],  when: gui_install}